finished
Marko2701/week-2-test pull request #1
Opened 2021-09-13 16:20 UTC by Marko2701

2021-09-14 08:21 UTC, chomii82 requested changes
U resursima koje si dobio imas i favicon. Ubaci i njega.

2021-09-15 07:03 UTC, sbozic85 requested changes
Treba jos malo da doteras responsive. Gledaja da izgleda po dizajnu na velicinama ekrana od 320px pa navise. Takodje, pogledaj i u landscape da se lepo prikazuje

2021-09-15 07:04 UTC, chomii82 commented on style.css
> +* {
Css je generalno ok. Moja sugestija bi bila da koristis CSS variables kad vec imas sve te vrednosti u style-guide.

2021-09-16 14:28 UTC, sbozic85 approved these changes

2021-09-16 14:28 UTC, merged